DROP TABLE IF EXISTS Guests;
DROP TABLE IF EXISTS Branches;
DROP TABLE IF EXISTS Establishments;


CREATE TABLE Guests
(
    Id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    Name VARCHAR(30) NOT NULL,
    PhoneNumber VARCHAR(20) NOT NULL
);

CREATE TABLE Establishments
(
    Id INT PRIMARY KEY NOT NULL IDENTITY(1,1),
    Name VARCHAR(30) NOT NULL,
    Type INT NOT NULL,
    Email VARCHAR(20) NOT NULL,
    Password TEXT NOT NULL
);


CREATE TABLE Branches
(
    Id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    EstablishmentId INT REFERENCES Establishments (Id),
    Address VARCHAR(30) NOT NULL
);
